package com.Laibin.SugarInventory.mapper;

import com.Laibin.SugarInventory.domain.dto.PalletTaskQueryDTO;
import com.Laibin.SugarInventory.domain.vo.PalletTaskPageVO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface PalletTaskQueryMapper {

    @Select({
            "<script>",
            "SELECT ",
            " t.id AS taskId, t.task_type AS taskType, t.biz_scene AS bizScene, t.status AS taskStatus,",
            " t.pallet_code_id AS palletCodeId, pc.code AS code,",
            " COALESCE(t.target_warehouse_id, fr.to_warehouse_id) AS targetWarehouseId,",
            " COALESCE(tw.warehouse_name, fw.warehouse_name) AS targetWarehouseName,",
            " COALESCE(t.target_side, fr.to_side) AS targetSide,",
            " t.product_id AS productId, p.product_name AS productName, p.product_type AS productType,",
            " t.product_status AS productStatus,",
            " CASE",
            "   WHEN poc.id IS NOT NULL THEN",
            "     CASE WHEN poc.unit = '1'",
            "       THEN COALESCE(poc.pieces, poc.quantity, 0) * COALESCE(p.weight_per_piece, 0)",
            "       ELSE COALESCE(poc.quantity, 1) * COALESCE(p.pieces_per_pallet, 0) * COALESCE(p.weight_per_piece, 0)",
            "     END",
            "   ELSE COALESCE(p.pieces_per_pallet, 0) * COALESCE(p.weight_per_piece, 0)",
            " END AS totalWeight,",
            " t.production_date AS productionDate,",
            " t.screen_mesh_id AS screenMeshId, sm.mesh_name AS screenMeshName,",
            " t.assay_id AS assayId, t.remark AS remark, t.operation_batch_no AS operationBatchNo,",
            " t.created_at AS createdAt, cu.name AS createdBy,",
            " t.confirmed_at AS confirmedAt, uu.name AS confirmedBy,",
            " COALESCE(si.cnt, 0) AS semiItemCount,",
            " poc.id AS productionOutputCodeId, poc.production_order_id AS productionOrderId,",
            " po.order_no AS productionOrderNo, po.order_type AS productionOrderType, po.status AS productionOrderStatus,",
            " poc.quantity AS productionOutputQuantity, poc.unit AS productionOutputUnit, poc.pieces AS productionOutputPieces,",
            " plb.batch_no AS productionLabelBatchNo",
            " FROM pallet_task t",
            " LEFT JOIN pallet_code pc ON t.pallet_code_id = pc.id",
            " LEFT JOIN product p ON t.product_id = p.id",
            " LEFT JOIN screen_mesh sm ON t.screen_mesh_id = sm.id",
            " LEFT JOIN warehouse tw ON t.target_warehouse_id = tw.id",
            " LEFT JOIN pallet_flow_record fr ON fr.task_id = t.id AND fr.operation_type IN ('SEMI_INSTOCK', 'FINISH_INSTOCK', 'TRANSFER')",
            " LEFT JOIN warehouse fw ON fr.to_warehouse_id = fw.id",
            " LEFT JOIN user cu ON t.created_by = cu.id",
            " LEFT JOIN user uu ON t.confirmed_by = uu.id",
            " LEFT JOIN (SELECT pallet_task_id, COUNT(*) AS cnt FROM pallet_task_semi_item GROUP BY pallet_task_id) si",
            "   ON t.id = si.pallet_task_id",
            " LEFT JOIN production_order_output_code poc ON poc.pallet_task_id = t.id AND poc.status != 'CANCELED'",
            " LEFT JOIN production_order po ON po.id = poc.production_order_id",
            " LEFT JOIN production_order_label_code plc ON plc.id = poc.label_code_id",
            " LEFT JOIN production_order_label_batch plb ON plb.id = plc.batch_id",
            " WHERE 1=1",
            "   AND t.cycle_no = pc.current_cycle_no",
            " <if test='q.code != null and q.code != \"\"'>",
            "   AND pc.code = #{q.code}",
            " </if>",
            " <if test='q.codes != null and q.codes != \"\"'>",
            "   AND FIND_IN_SET(pc.code, #{q.codes})",
            " </if>",
            " <if test='q.taskType != null and q.taskType != \"\"'>",
            "   <choose>",
            "     <when test='q.taskType == \"IN\"'>",
            "       AND t.task_type IN ('SEMI_IN', 'FINISH_IN')",
            "     </when>",
            "     <otherwise>",
            "       AND t.task_type = #{q.taskType}",
            "     </otherwise>",
            "   </choose>",
            " </if>",
            " <if test='q.bizScene != null and q.bizScene != \"\"'>",
            "   AND t.biz_scene = #{q.bizScene}",
            " </if>",
            " <if test='q.status != null and q.status != \"\"'>",
            "   AND t.status = #{q.status}",
            " </if>",
            " <if test='q.productId != null'>",
            "   AND t.product_id = #{q.productId}",
            " </if>",
            " <if test='q.productNameExact != null and q.productNameExact != \"\"'>",
            "   AND p.product_name = #{q.productNameExact}",
            " </if>",
            " <if test='(q.productNameExact == null or q.productNameExact == \"\") and q.productName != null and q.productName != \"\"'>",
            "   AND p.product_name LIKE CONCAT('%', #{q.productName}, '%')",
            " </if>",
            " <if test='q.productType != null and q.productType != \"\"'>",
            "   AND p.product_type = #{q.productType}",
            " </if>",
            " <if test='q.productStatus != null and q.productStatus != \"\"'>",
            "   AND t.product_status = #{q.productStatus}",
            " </if>",
            " <if test='q.targetWarehouseName != null and q.targetWarehouseName != \"\"'>",
            "   AND (tw.warehouse_name LIKE CONCAT('%', #{q.targetWarehouseName}, '%')",
            "        OR fw.warehouse_name LIKE CONCAT('%', #{q.targetWarehouseName}, '%'))",
            " </if>",
            " <if test='q.productionDateStart != null'>",
            "   AND t.production_date &gt;= #{q.productionDateStart}",
            " </if>",
            " <if test='q.productionDateEnd != null'>",
            "   AND t.production_date &lt;= #{q.productionDateEnd}",
            " </if>",
            " ORDER BY t.created_at DESC",
            " LIMIT #{offset}, #{size}",
            "</script>"
    })
    List<PalletTaskPageVO> pageTasks(@Param("q") PalletTaskQueryDTO q,
                                     @Param("offset") long offset,
                                     @Param("size") long size);

    @Select({
            "<script>",
            "SELECT COUNT(*)",
            " FROM pallet_task t",
            " LEFT JOIN pallet_code pc ON t.pallet_code_id = pc.id",
            " LEFT JOIN product p ON t.product_id = p.id",
            " LEFT JOIN warehouse tw ON t.target_warehouse_id = tw.id",
            " LEFT JOIN pallet_flow_record fr ON fr.task_id = t.id AND fr.operation_type IN ('SEMI_INSTOCK', 'FINISH_INSTOCK', 'TRANSFER')",
            " LEFT JOIN warehouse fw ON fr.to_warehouse_id = fw.id",
            " WHERE 1=1",
            "   AND t.cycle_no = pc.current_cycle_no",
            " <if test='q.code != null and q.code != \"\"'>",
            "   AND pc.code = #{q.code}",
            " </if>",
            " <if test='q.codes != null and q.codes != \"\"'>",
            "   AND FIND_IN_SET(pc.code, #{q.codes})",
            " </if>",
            " <if test='q.taskType != null and q.taskType != \"\"'>",
            "   <choose>",
            "     <when test='q.taskType == \"IN\"'>",
            "       AND t.task_type IN ('SEMI_IN', 'FINISH_IN')",
            "     </when>",
            "     <otherwise>",
            "       AND t.task_type = #{q.taskType}",
            "     </otherwise>",
            "   </choose>",
            " </if>",
            " <if test='q.bizScene != null and q.bizScene != \"\"'>",
            "   AND t.biz_scene = #{q.bizScene}",
            " </if>",
            " <if test='q.status != null and q.status != \"\"'>",
            "   AND t.status = #{q.status}",
            " </if>",
            " <if test='q.productId != null'>",
            "   AND t.product_id = #{q.productId}",
            " </if>",
            " <if test='q.productNameExact != null and q.productNameExact != \"\"'>",
            "   AND p.product_name = #{q.productNameExact}",
            " </if>",
            " <if test='(q.productNameExact == null or q.productNameExact == \"\") and q.productName != null and q.productName != \"\"'>",
            "   AND p.product_name LIKE CONCAT('%', #{q.productName}, '%')",
            " </if>",
            " <if test='q.productType != null and q.productType != \"\"'>",
            "   AND p.product_type = #{q.productType}",
            " </if>",
            " <if test='q.productStatus != null and q.productStatus != \"\"'>",
            "   AND t.product_status = #{q.productStatus}",
            " </if>",
            " <if test='q.targetWarehouseName != null and q.targetWarehouseName != \"\"'>",
            "   AND (tw.warehouse_name LIKE CONCAT('%', #{q.targetWarehouseName}, '%')",
            "        OR fw.warehouse_name LIKE CONCAT('%', #{q.targetWarehouseName}, '%'))",
            " </if>",
            " <if test='q.productionDateStart != null'>",
            "   AND t.production_date &gt;= #{q.productionDateStart}",
            " </if>",
            " <if test='q.productionDateEnd != null'>",
            "   AND t.production_date &lt;= #{q.productionDateEnd}",
            " </if>",
            "</script>"
    })
    Long countTasks(@Param("q") PalletTaskQueryDTO q);
}

