package com.Laibin.SugarInventory.mapper;

import com.Laibin.SugarInventory.domain.dto.PalletCodeQueryDTO;
import com.Laibin.SugarInventory.domain.dto.FixedProductPoolQueryDTO;
import com.Laibin.SugarInventory.domain.vo.FixedProductQrPoolVO;
import com.Laibin.SugarInventory.domain.vo.PalletCodePageVO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface PalletCodeQueryMapper {

    @Select({
            "<script>",
            "SELECT ",
            " pc.id, pc.code, pc.status,",
            " CASE WHEN pc.status = 'FREE' THEN pc.fixed_product_id ELSE pc.product_id END AS productId,",
            " CASE WHEN pc.status = 'FREE' THEN NULL ELSE pc.product_status END AS productStatus,",
            " CASE WHEN pc.status = 'FREE' THEN NULL ELSE pc.production_date END AS productionDate,",
            " CASE WHEN pc.status = 'FREE' THEN NULL ELSE pc.assay_id END AS assayId,",
            " pc.created_at AS createdAt, pc.updated_at AS updatedAt,",
            " CASE WHEN pc.status = 'FREE' THEN NULL ELSE p.product_name END AS productName,",
            " CASE WHEN pc.status = 'FREE' THEN NULL ELSE p.product_type END AS productType,",
            " CASE WHEN pc.status = 'FREE' THEN NULL ELSE sm.mesh_name END AS screenMeshName,",
            " cu.name AS createdByName, uu.name AS updatedByName",
            " FROM pallet_code pc",
            " LEFT JOIN product p ON pc.product_id = p.id",
            " LEFT JOIN screen_mesh sm ON pc.screen_mesh_id = sm.id",
            " LEFT JOIN user cu ON pc.created_by = cu.id",
            " LEFT JOIN user uu ON pc.updated_by = uu.id",
            " WHERE 1=1",
            " <if test='q.code != null and q.code != \"\"'>",
            "   AND pc.code = #{q.code}",
            " </if>",
            " <if test='q.status != null and q.status != \"\"'>",
            "   AND pc.status = #{q.status}",
            " </if>",
            " <if test='q.productName != null and q.productName != \"\"'>",
            "   AND pc.status &lt;&gt; 'FREE'",
            "   AND p.product_name LIKE CONCAT('%', #{q.productName}, '%')",
            " </if>",
            " <if test='q.productType != null and q.productType != \"\"'>",
            "   AND pc.status &lt;&gt; 'FREE'",
            "   AND p.product_type = #{q.productType}",
            " </if>",
            " <if test='q.productStatus != null and q.productStatus != \"\"'>",
            "   AND pc.status &lt;&gt; 'FREE'",
            "   AND pc.product_status = #{q.productStatus}",
            " </if>",
            " <if test='q.productionDateStart != null'>",
            "   AND pc.status &lt;&gt; 'FREE'",
            "   AND pc.production_date &gt;= #{q.productionDateStart}",
            " </if>",
            " <if test='q.productionDateEnd != null'>",
            "   AND pc.status &lt;&gt; 'FREE'",
            "   AND pc.production_date &lt;= #{q.productionDateEnd}",
            " </if>",
            " <if test='q.inventoryOnly != null and q.inventoryOnly'>",
            "   AND EXISTS (SELECT 1 FROM inventory i WHERE i.pallet_code_id = pc.id)",
            " </if>",
            " ORDER BY CASE pc.status",
            "   WHEN 'PENDING' THEN 1",
            "   WHEN 'INSTOCK' THEN 2",
            "   WHEN 'FREE' THEN 3",
            "   WHEN 'INVALID' THEN 4",
            "   ELSE 5",
            " END, pc.created_at DESC, pc.id DESC",
            " LIMIT #{offset}, #{size}",
            "</script>"
    })
    java.util.List<PalletCodePageVO> pagePalletCodes(@Param("q") PalletCodeQueryDTO q,
                                                     @Param("offset") long offset,
                                                     @Param("size") long size);

    @Select({
            "<script>",
            "SELECT COUNT(*)",
            " FROM pallet_code pc",
            " LEFT JOIN product p ON pc.product_id = p.id",
            " WHERE 1=1",
            " <if test='q.code != null and q.code != \"\"'>",
            "   AND pc.code = #{q.code}",
            " </if>",
            " <if test='q.status != null and q.status != \"\"'>",
            "   AND pc.status = #{q.status}",
            " </if>",
            " <if test='q.productName != null and q.productName != \"\"'>",
            "   AND pc.status &lt;&gt; 'FREE'",
            "   AND p.product_name LIKE CONCAT('%', #{q.productName}, '%')",
            " </if>",
            " <if test='q.productType != null and q.productType != \"\"'>",
            "   AND pc.status &lt;&gt; 'FREE'",
            "   AND p.product_type = #{q.productType}",
            " </if>",
            " <if test='q.productStatus != null and q.productStatus != \"\"'>",
            "   AND pc.status &lt;&gt; 'FREE'",
            "   AND pc.product_status = #{q.productStatus}",
            " </if>",
            " <if test='q.productionDateStart != null'>",
            "   AND pc.status &lt;&gt; 'FREE'",
            "   AND pc.production_date &gt;= #{q.productionDateStart}",
            " </if>",
            " <if test='q.productionDateEnd != null'>",
            "   AND pc.status &lt;&gt; 'FREE'",
            "   AND pc.production_date &lt;= #{q.productionDateEnd}",
            " </if>",
            " <if test='q.inventoryOnly != null and q.inventoryOnly'>",
            "   AND EXISTS (SELECT 1 FROM inventory i WHERE i.pallet_code_id = pc.id)",
            " </if>",
            "</script>"
    })
    Long countPalletCodes(@Param("q") PalletCodeQueryDTO q);

    @Select({
            "<script>",
            "SELECT",
            " pc.id, pc.code, pc.fixed_product_id AS fixedProductId,",
            " p.product_name AS fixedProductName,",
            " pc.status, pc.fixed_mode_enabled AS fixedModeEnabled,",
            " CASE WHEN pc.status = 'FREE' THEN 1 ELSE 0 END AS allowPrint,",
            " pc.updated_at AS updatedAt",
            " FROM pallet_code pc",
            " INNER JOIN product p ON pc.fixed_product_id = p.id",
            " WHERE pc.fixed_mode_enabled = 1",
            " <if test='q.productId != null'>",
            "   AND pc.fixed_product_id = #{q.productId}",
            " </if>",
            " <if test='q.productName != null and q.productName != \"\"'>",
            "   AND p.product_name LIKE CONCAT('%', #{q.productName}, '%')",
            " </if>",
            " <if test='q.codes != null and q.codes != \"\"'>",
            "   AND FIND_IN_SET(pc.code, #{q.codes})",
            " </if>",
            " <if test='q.status != null and q.status != \"\"'>",
            "   AND pc.status = #{q.status}",
            " </if>",
            " <if test='q.freeOnly != null and q.freeOnly'>",
            "   AND pc.status = 'FREE'",
            " </if>",
            " ORDER BY pc.updated_at DESC, pc.id DESC",
            " LIMIT #{offset}, #{size}",
            "</script>"
    })
    java.util.List<FixedProductQrPoolVO> pageFixedProductPool(@Param("q") FixedProductPoolQueryDTO q,
                                                              @Param("offset") long offset,
                                                              @Param("size") long size);

    @Select({
            "<script>",
            "SELECT COUNT(*)",
            " FROM pallet_code pc",
            " INNER JOIN product p ON pc.fixed_product_id = p.id",
            " WHERE pc.fixed_mode_enabled = 1",
            " <if test='q.productId != null'>",
            "   AND pc.fixed_product_id = #{q.productId}",
            " </if>",
            " <if test='q.productName != null and q.productName != \"\"'>",
            "   AND p.product_name LIKE CONCAT('%', #{q.productName}, '%')",
            " </if>",
            " <if test='q.codes != null and q.codes != \"\"'>",
            "   AND FIND_IN_SET(pc.code, #{q.codes})",
            " </if>",
            " <if test='q.status != null and q.status != \"\"'>",
            "   AND pc.status = #{q.status}",
            " </if>",
            " <if test='q.freeOnly != null and q.freeOnly'>",
            "   AND pc.status = 'FREE'",
            " </if>",
            "</script>"
    })
    Long countFixedProductPool(@Param("q") FixedProductPoolQueryDTO q);
}
