spring:
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/laibin?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ssmrcury1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    mapper:
      sort-properties-alphabetically: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      order-map-entries-by-keys: false
server:
  port: 8080
wechat:
  appid: wxb2e24e10a7cb3ef8
  secret: 0e992128f83b91b6e618da3151f108f7
jwt:
  secret: xVqyO+0aawRF/LNpEjDDe1w/VXjnbgjJsm43uq0dbpTTt5EHbldZ3FLohntYJfRlXAhW2ZNww27q04Ja2C9kNw==
  expiration: 86400000
user:
  dir: D:\\Laibin\\LaibinSugarInventory
file:
  export-dir: D:\\Laibin\\Files
  base-url: https://cscgood.mynatapp.cc
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework.aop: DEBUG
  type-handlers-package: com.Laibin.SugarInventory.util
  global-config:
    db-config:
      logic-delete-field: deleted
      id-type: auto