spring:
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/laibin?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ssmrcury1
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000       # 连接最大存活时间（建议比 MySQL 的 wait_timeout 短，单位毫秒）
      connection-timeout: 30000 # 连接超时时间（毫秒）
      idle-timeout: 30000       # 空闲连接超时时间（毫秒）
      validation-timeout: 5000  # 连接验证超时时间（毫秒）
      leak-detection-threshold: 60000 # 检测连接泄漏（毫秒）
      connection-test-query: SELECT 1  # MySQL 连接测试语句
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  jackson:
    mapper:
      sort-properties-alphabetically: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      order-map-entries-by-keys: false
knife4j:
  enable: true
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
server:
  port: 8080
wechat:
  appid: wxb2e24e10a7cb3ef8
  secret: 0e992128f83b91b6e618da3151f108f7
openai:
  api-url: https://www.dmxapi.com/v1
  api-key: ${OPENAI_API_KEY}
jwt:
  secret: xVqyO+0aawRF/LNpEjDDe1w/VXjnbgjJsm43uq0dbpTTt5EHbldZ3FLohntYJfRlXAhW2ZNww27q04Ja2C9kNw==
  expiration: 86400000
user:
  dir: D:\\Laibin\\LaibinSugarInventory
file:
  export-dir: D:\\Laibin\\Files
  base-url: https://cscgood.mynatapp.cc
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework.aop: DEBUG
  type-handlers-package: com.Laibin.SugarInventory.util
  global-config:
    db-config:
      logic-delete-field: deleted
      id-type: auto
