CREATE TABLE IF NOT EXISTS agent_finish_inbound_execution_preview (
    id BIGINT NOT NULL AUTO_INCREMENT,
    preview_ref VARCHAR(64) NOT NULL,
    owner_user_id INT NOT NULL,
    agent_session_id VARCHAR(64) DEFAULT NULL,
    preview_version INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    required_permissions VARCHAR(200) NOT NULL,
    entity_refs_json TEXT NOT NULL,
    normalized_input_json LONGTEXT NOT NULL,
    entity_state_json LONGTEXT NOT NULL,
    public_payload_json LONGTEXT NOT NULL,
    state_digest CHAR(64) NOT NULL,
    normalized_request_sha256 CHAR(64) NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    previewed_at DATETIME(6) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    revoked_at DATETIME(6) DEFAULT NULL,
    consumed_at DATETIME(6) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_finish_inbound_preview_ref (preview_ref),
    KEY idx_agent_finish_inbound_preview_owner_created (owner_user_id, created_at),
    KEY idx_agent_finish_inbound_preview_session_status (agent_session_id, status),
    KEY idx_agent_finish_inbound_preview_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
